export const BRANCHES = [
  'Core Team',
  'GD Road',
  'NCH Group',
  'Katargam',
  'Management',
  'Vesu',
  'Navsari',
  'Navsari Night Shift',
  'Valsad',
  'NSPL HO',
  'Katargam Night Shift',
  'Mumbai Andheri',
  'NSPL OSC',
  'Intern',
  'Rajkot',
  'Inventory',
  'Engineer',
  'JobWork',
  'Marketing',
  'Customer Care',
  'Resin & Tray',
  'Admin',
];
